---
# tasks file for molecule-validate-neutron-deploy

- name: Create python2 virtualenv for the submodule
  shell: virtualenv /opt/molecule-test-env-on-sut
  when:
    - rpc_product_release != "master" or
      rpc_product_release != "rocky"

- name: Create python3 virtualenv for the submodule
  shell: virtualenv --python=python3 /opt/molecule-test-env-on-sut
  when:
    - rpc_product_release == "master" or
      rpc_product_release == "rocky"

- name: Install python modules into /opt/molecule-test-env-on-sut virtualenv
  pip:
    name: "{{ item }}"
    extra_args: --isolated
    state: present
    virtualenv: /opt/molecule-test-env-on-sut
  with_items:
    - ansible==2.5.5
    - shade==1.28.0
    - ipaddr==2.2.0
    - netaddr==0.7.19
