---
# tasks file for molecule-validate-neutron-deploy

- import_tasks: cloning_openstack_ansible_ops.yml
  when: ansible_local.service_setup is not defined

- import_tasks: create_virtualenv_on_sut.yml
  when: ansible_local.service_setup is not defined

- import_tasks: run_openstack_service_setup_playbook.yml
  when: ansible_local.service_setup is not defined
